{"CONSUMER_KEY":"dx61hPNdXBOUsbl0eY9dpnId3",
"CONSUMER_SECRET":"JNgPlrDlLAHOApFop1817CAXdySkzjTliRHgGcPSllr2k2qV08",
"ACCESS_TOKEN":"834101552994406400-2V4yEieR0imWj73J0nnnBqUG9qzNW2q",
"ACCESS_TOKEN_SECRET":"pX3DpazVnSP9rwrPx1zMynV15QVdHunvgxH2fcFwHO0Dc"}
